### ISSUE TITLE
Parameter Configs for Code Blocks no longer work properly

### ISSUE THREAD

**Issue by benjivesterby** [razonyang/hugo-theme-bootstrap#449]
**Describe the bug**
CodeBlock settings are no longer working with the release of hugo pipes. Only default values are ever used regardless of configuration. I believe that this is related to a missing reference in the files. I am attempting to resolve this locally to push a PR but I am not familiar with this level of adjustment in the theme. It might be an easy fix but I'm currently unable to figure it out. 

**To Reproduce**
Change default settings for code block, and see if they change. This also likely affects utterances as I believe the issue is that there is a missing linkage in the new hugo pipes setup. 

**Expected behavior**
The code block should adhere to the settings

**Screenshots**
Screenshot showing code block limited to 7 lines. 
![Screenshot 2022-03-18 06:31:39](https://user-images.githubusercontent.com/977134/158987264-8beb58a4-141f-4699-b28b-0ad4f740a1e8.png)

Screenshot showing config
![Screenshot 2022-03-18 06:36:12](https://user-images.githubusercontent.com/977134/158987899-a3104af4-bda6-402b-930c-0bd384155036.png)

**Hugo version:**
0.95 Extended

**Theme version:**
Master branch

**Desktop (please complete the following information):**
 - Linux
 - Chrome
 - Latest

**Comment by razonyang** [comment]
Thank you.

**Comment by benjivesterby** [comment]
I should have mentioned this bug also affects the line numbers setting which can also be seen in the screenshots.

**Comment by razonyang** [comment]
Sorry, I missed it. Should be fixed by 7b87775.

**Comment by sagarbehere** [comment]
@razonyang I am seeing the same issue with v1.5.8 and Hugo version 0.118.2-extended. The parameter settings for code blocks have no effect. In my params.yaml file, the configuration is
```
codeBlock:
  maxLines: 10
  lineNos: true 
```
But the code block are still showing the full code block (more than 10 lines) and no line numbers.

**Comment by razonyang** [comment]
@sagarbehere Could you please provide a public repo for quick reproducing and debuging?

**Comment by razonyang** [comment]
Confirmed, it's a configuration issue, to fix it, you'll need to set the following configuration on `config` or `hugo` config file, take YAML as an example.

```yaml
markup:
  highlight:
    lineNos: true # required
    noClasses: false # required
    lineNumbersInTable: false # required
```

Please also enable the `codeBlock.lineNos` as `true` on `params` config file as well.

Example commit: https://github.com/razonyang/hugo-theme-bootstrap-skeleton/commit/e208df43e4f0673615858a2af8a60cc7ac63cf03.

**Comment by sagarbehere** [comment]
@razonyang Hmm, that isn't helping. I added the following to `config.yaml`
```
markup:
  highlight:
    lineNos: true # required
    noClasses: false # required
    lineNumbersInTable: false # required
```

and my `params.yaml` has
```
codeBlock:
  maxLines: 10
  lineNos: true
```
But there is no change in the codeblocks. They are still showing all the lines (more than 10) and no line numbers.

**Comment by razonyang** [comment]
@sagarbehere does restarting Hugo server help? I just tested this configuration minutes ago. If not, please provide access to your site repo.

**Comment by sagarbehere** [comment]
@razonyang restarting Hugo server does not help. I will make an example repo and send you the links in a couple of hours.

**Comment by sagarbehere** [comment]
@razonyang I did exactly the following on an Ubuntu 22.04 system, with Hugo 0.118.2 extended and go version `go1.23.0 linux/amd64`

1. `git clone https://github.com/razonyang/hugo-theme-bootstrap-skeleton /tmp/hbs-skeleton`
2. `cd /tmp/hbs-skeleton`
3. Confirmed that `config/_default/config.yaml` has the text
```
markup:
  highlight:
    lineNos: true
    noClasses: false
    lineNumbersInTable: false
```
4. Confirmed that `config/_default/params.yaml` has the text
```
codeBlock:
  # maxLines: 8
  lineNos: true 
```
5. Copy the attached file, `Plausible.md` to `content/docs/`.
6. `hugo mod npm pack`
7. `npm install`
8. `hugo server`
9. Browse to `localhost:1313/docs/plausible`

When I do this, the screenshot is shown below. The code block has no line numbers and is not having the default maxLines = 7.

(By the way, `hugo server` does not work without doing steps 7 and 8 above. Perhaps those steps should be added to the instructions of the skeleton theme?)
![codblock](https://github.com/user-attachments/assets/aed605ac-0f94-490a-ba04-618f6d28b778)



[Plausible.md](https://github.com/user-attachments/files/16650270/Plausible.md)

**Comment by razonyang** [comment]
@sagarbehere I see, the cause is that you need to specify the [code fence](https://gohugo.io/content-management/syntax-highlighting/#highlighting-in-code-fences), such as `sh`, `docker` in this case.

````
```sh
mkdir ...
...
```

```docker
version: "3.3"
...
```
````

**Comment by sagarbehere** [comment]
@razonyang Interesting. I specified `docker` in the code fence, and now I can see the line numbers.

However, I am not able to see the impact of `maxLines: 8` . I still see the full code block. Actually, it is stranger than that. The very first time I loaded the page, I recall seeing the code block limited to 8 lines and with line numbers.. exactly as it should be. But after I hit refresh a few times, the line limitation disappeared and now only the entire code black with all lines is visible. So after refreshing the page a few times, the `maxLines: 8` seems to not work? Are you seeing this behavior on your side too?

**Comment by razonyang** [comment]
@sagarbehere it work.

![image](https://github.com/user-attachments/assets/bb9a6c53-c6b9-4a35-b470-e2c036bd0ef2)

**Comment by sagarbehere** [comment]
@razonyang 

Which browser are you using? I am using Firefox on Linux. I hope you are able to see the attached screenrecording video. As you can see in the video, the only thing I am doing is clicking "Refresh" and then you see that sometimes the whole code block can be seen and sometimes only 8 lines can be seen. I am making no changes, except refreshing the page.

https://github.com/user-attachments/assets/0695cad2-0e50-485e-a8b4-716ffbb9eaec

**Comment by razonyang** [comment]
It looks like the JS not ready to execute (refresh too fast) or failed to execute (please post the log from browser console).

The maxlines is implemented by JS, it will show full height of the code block, once the JS was loaded, and it will be executed and determind maximum lines, and then change code block height.

**Comment by sagarbehere** [comment]
@razonyang 

> It looks like the JS not ready to execute (refresh too fast) or failed to execute (please post the log from browser console).

See below the image from the browser console. I think the relevant message is the line
```
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content.
```
This message does not appear in the cases where the code block is correctly restricted to 8 lines.

![LayoutForced](https://github.com/user-attachments/assets/ba62d602-f125-47e8-a257-59f1df28dc13)

**Comment by razonyang** [comment]
@sagarbehere yes, that is the cause, should be fixed in v1.6.2, please clear browser cache after upgrading theme, and then try again.

**Comment by sagarbehere** [comment]
@razonyang Yes, v1.6.2 fixes the issue.

1. Is it possible to make this work without specifying the code fence with `sh` or `docker` etc.? Because it was working perfectly with my older theme version. Now I need to modify all my files just because I upgraded the theme. I will do it, but it would be nice if it can continue working without requiring modifications. Maybe we can assume a default type of code fence if the specification is missing? Also, I don't think the markdown specification absolutely requires a code fence specification. So we may be breaking compatibility a little bit.
2. If 1 above is not possible, where can I find a list of possible values to specify the code fence? You pointed out that `sh` and `docker` are possibilities? What else? `python`? `javascript`? Is there a complete list somewhere?

Thank you for the quick fixes.

**Comment by razonyang** [comment]
> Is it possible to make this work without specifying the code fence with sh or docker etc

I may fix it, but low priority, track on #1052. But you should always specify the code fence, since the highlighting styles are applied on code fence.

Please file another issue if you have other questions or requests.
